name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t wallpaper-hub .

      - name: Run Docker container (for testing)
        run: docker run -d -p 80:80 wallpaper-hub

      - name: Deployment placeholder
        run: echo "🚀 Deploying wallpaper-hub... done!"
